spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://yhao-mysql.mysql.rds.aliyuncs.com:3306/gam-chat?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true
    username: yhao
    password: ENC(xS2vxIknJHjN0wBwiZH7iKhFDCvlp0Lb)

  #redis
  redis:
    host: localhost
    port: 6379
    database: 0
  mail:
    host: smtp.gmail.com
    username: kinker.notic@gmail.com
    #Gmail账号密码
#    password: ENC(h+VFjVzMjRPdUoaYSr8CYpg5XXtq/b/5)
    password: rcdobuzcmjvqfxih
#    protocol: smtp
    properties.mail.smtp.auth: true
    properties.mail.transport.protocol: smtp
    properties.mail.display.sendmail: kinker
    properties.mail.display.sendname: kinker
    properties.mail.smtp.connectiontimeout: 5000
    properties.mail.smtp.timeout: 5000
    properties.mail.smtp.writetimeout: 5000
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    properties.mail.smtp.socketFactory.port: 465
    properties.mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
    from: kinker.notic@gmail.com
    nickname: kinker
    default-encoding: utf-8

